title: Harry Man # your name (or website title) here
logo: "/images/harrymandeveloper.jpg" # your photo (or logo) here
description: > A versatile, positive and creative JavaScript and PHP Developer with first rate communication and interpersonal skills. 
An award-winning writer with an established artistic practice, and a PTC-certified copyeditor, proofreader and copywriter alongside
training in eloquent Laravel, APIs, PHP, React, HTML, CSS, and JavaScript. Experience working collaboratively, designing applications and communicating with a variety of stakeholders.
  <a href="https://www.linkedin.com/in/harry-man-developer/">View My LinkedIn Profile</a> 
  
google_analytics: UA-24021869-2 # your Google Analytics tracking ID here
