title: Harry Man # your name (or website title) here
logo: "./images/harrymandeveloper.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b> A versatile, positive and creative JavaScript and PHP Developer with first rate communication and interpersonal skills.</b>
  <br><br>
  <center><a href="https://github.com/harrymandeveloper">GitHub</a><br>
  <a href="https://www.linkedin.com/in/harry-man-developer/">LinkedIn</a><br>
  <a href="https://www.twitter.com/harrymantweets">Twitter</a><br> 
  <a href="https://www.instagram.com/harrymantweets">Instagram</a><br></center>

  
theme: jekyll-theme-minimal
google_analytics: UA-24021869-2 # your Google Analytics tracking ID here
